blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Glorktelligence/Claude-AI-Export-Renderer/blob/main/README.md
    about: Read the project documentation and user guide
  - name: Development Guide
    url: https://github.com/Glorktelligence/Claude-AI-Export-Renderer/blob/main/CLAUDE.md
    about: Technical documentation for contributors
  - name: Security Policy
    url: https://github.com/Glorktelligence/Claude-AI-Export-Renderer/blob/main/SECURITY.md
    about: Report security vulnerabilities
